import * as THREE from 'three';

import { evaluateAnimationTrack, evaluateAnimationTrackStep } from '../particle/tracks';

/**
 * ONE M2 RIBBON EMITTER'S SIMULATION -- the edge ring, and nothing that touches the GPU.
 *
 * A ribbon is how the game draws a trail: a lightning bolt, a weapon enchant streamer, a wisp's tail.
 * `Spells\LightningBolt_Missile.mdx` is **three ribbons and zero particle emitters**, which is why the
 * owner's projectile reads as a static texture -- this client rendered no ribbons at all, so a mesh in
 * bind pose was standing in for the trail.
 *
 * ## The mechanism is the reference's, and it IS implemented there
 *
 * Checked before a line was written, because the brief said to stop if it was not: the reference has
 * `benilla-formats/src/ribbons.rs` (the record), `benilla-formats/tests/ribbons.rs` and
 * `benilla-world/src/ribbons.rs` (the simulation). So this is a port.
 *
 * `benilla-world/src/ribbons.rs:3-12`: "the 1.12 client simulates a ribbon as a ring of **edges**:
 * each frame the emitter's bone-local origin is transformed by the live bone matrix into a node point,
 * `floor(dt*edgesPerSecond + phase)` new edges (a vertex pair at `+/-heightAbove/heightBelow` across
 * the node) are committed and backdated inside the frame, old edges age out at `edgeLifetime`,
 * **gravity carries the stored verts along world +Z by `g*t^2`** -- up for the positive majority of
 * the corpus -- and the edge list renders as a triangle strip whose `u` texcoord slides with edge age
 * (the texture's transparent tail fades the trail)."
 *
 * Ring capacity is the reference's `ceil(rate*lifetime)+2` with `MAX_EDGES` as a backstop
 * (`ribbons.rs:33-35`).
 *
 * **IT DOES NOT DEPEND ON POSING THE EFFECT MODEL**, which is why it is worth doing first. The node
 * comes from the bone's WORLD matrix, so a missile's trail is generated by the missile MOVING --
 * bind-pose bones are fine -- and a hand ribbon rides the character's own animated hand.
 *
 * ## The record layout is v264 and was MEASURED, not assumed
 *
 * The reference's spec is build 5875 / MD20 v256 with a record stride of **0xdc = 220 bytes**
 * (`benilla-formats/src/ribbons.rs:9-19`); this build's record is **176**
 * (`wow-data-parser/m2/particle/ribbon.js`). The 44-byte delta is fully accounted for: each of the six
 * `M2Track`s lost its `interpolationRanges` array between the versions (28 B -> 20 B, six times = 48)
 * and v264 added back `priorityPlane`/`ribbonColorIndex`/`textureTransformLookupIndex` (4 B).
 *
 * Validated against served bytes in `world/__bench__/effect-emitter-probe.test.ts`, which decodes
 * `LightningBolt_Missile.m2` and asserts every field lands in range -- a stride error walks each record
 * into the middle of the previous one, so three sane records is the residual:
 *
 *     ribbons=3  bones=26  textures=4  materials=4
 *     ribbon 0  bone=23  pos=[ 0.034, -0.239, -0.010]  edgesPerSec=50  edgeLife=0.100  gravity=0
 *     ribbon 1  bone=24  pos=[-0.174,  0.019,  0.051]  edgesPerSec=50  edgeLife=0.100  gravity=0
 *     ribbon 2  bone=25  pos=[-0.054, -0.117, -0.298]  edgesPerSec=50  edgeLife=0.200  gravity=0
 *
 * ## Frame cost, from those measured numbers rather than estimated
 *
 * Ring capacity is `ceil(50*0.1)+2 = 7` edges for two of them and `ceil(50*0.2)+2 = 12` for the third,
 * so a lightning bolt holds **26 edges across three ribbons** -- 23 segments, 92 vertices. Per ribbon
 * per frame: six track samples, one matrix-transform of a single point, ~1 edge committed
 * (`50/60 = 0.83`), ~1 aged out, and a rewrite of at most `capacity` vertex pairs into a **reused**
 * `Float32Array`.
 *
 * **No allocation on the steady path**: the ring is a fixed array of preallocated edge records, the two
 * scratch vectors are module-level, and the geometry buffers are sized once -- the discipline
 * `ParticleBatch` established, rather than a second one.
 *
 * For scale: `ParticleBatch#pack` writes 13 floats per instance across up to 512 instances, while a
 * whole lightning bolt's ribbons write ~92 vertices. The ribbon lane is the cheaper by an order of
 * magnitude, and it is bounded by `MAX_EDGES` per ribbon whatever the data says.
 */

/** The reference's backstop against a pathological rate x lifetime (`ribbons.rs:33-35`). */
export const MAX_EDGES = 512;

/**
 * `edgeLifetime` is clamped to at least this. THE REFERENCE'S RULE, and it bites on real data: the
 * measured lightning ribbons ship 0.100 and 0.200, both BELOW the clamp, so without it their trails
 * would be between a third and a half as long as the client draws them
 * (`benilla-formats/src/ribbons.rs:16`, "edgeLifetime(f32, clamped >= 0.25)").
 */
export const MIN_EDGE_LIFETIME = 0.25;

/** fixed16: the parser leaves the raw 0..32767 and states a consumer must divide (`ribbon.js`). */
const FIXED16_SCALE = 32767;

/** One committed edge: the vertex pair across the node, in world space, and its age. */
export interface RibbonEdge {
  /** Upper vertex (node + up * heightAbove). */
  ax: number; ay: number; az: number;
  /** Lower vertex (node - up * heightBelow). */
  bx: number; by: number; bz: number;
  /** Seconds since birth. Advanced per frame; dropped past `lifetime`. */
  age: number;
  /** Live only between a commit and the drop. */
  used: boolean;
}

const scratchNode = new THREE.Vector3();
const scratchUp = new THREE.Vector3();

/**
 * One live ribbon. Built per (instance, ribbon definition) pair by the manager, stepped once a frame,
 * and read by the batch.
 */
export class RibbonRuntime {
  readonly definition: any;

  /** `ceil(rate * lifetime) + 2`, clamped to `MAX_EDGES` -- the reference's ring capacity. */
  readonly capacity: number;

  /** `edgeLifetime` after the reference's clamp, in seconds. */
  readonly lifetime: number;

  /** Ring storage, allocated once. `head` indexes the newest edge. */
  private edges: RibbonEdge[];

  private head = 0;

  private liveCount = 0;

  /**
   * Fractional edge carried between frames, so a 50/sec ribbon at 60 fps commits one edge on most
   * frames and none on the rest -- rather than truncating to zero every frame and never emitting.
   */
  private phase = 0;

  /** The animation time the tracks sample at, self-driven like `RuntimeEmitter#advance`. */
  private timeMs = 0;

  constructor(definition: any) {
    this.definition = definition;
    const rate = Math.max(0, Number(definition.edgesPerSecond) || 0);
    this.lifetime = Math.max(MIN_EDGE_LIFETIME, Number(definition.edgeLifetime) || 0);
    this.capacity = Math.max(2, Math.min(MAX_EDGES, Math.ceil(rate * this.lifetime) + 2));
    this.edges = new Array(this.capacity);
    for (let i = 0; i < this.capacity; i += 1) {
      this.edges[i] = {
        ax: 0, ay: 0, az: 0, bx: 0, by: 0, bz: 0, age: 0, used: false,
      };
    }
  }

  /** How many edges are committed. The batch draws `max(0, live - 1)` segments. */
  get live(): number {
    return this.liveCount;
  }

  /**
   * The gate byte, sampled STEP because a `u8` track is never blended
   * (`benilla-formats/src/ribbons.rs:26-28`). Default 1: the reference's loader default is 1 and its
   * ctor 0, and clearing it "kills the whole ribbon's draw".
   */
  get visible(): boolean {
    return evaluateAnimationTrackStep(this.definition.visibilityTrack, 0, this.timeMs, 1) !== 0;
  }

  /**
   * Advance one frame.
   *
   * `boneMatrix` is the emitter bone's WORLD matrix. The node is the definition's bone-local
   * `position` pushed through it, which is what lets a moving model generate a trail without anything
   * posing the model itself.
   *
   * Deliberately NOT backdating sub-frame edge positions the way the reference does within one frame:
   * at 50 edges/sec and 60 fps at most one edge is committed per frame, so there is nothing to
   * distribute. Named rather than silently skipped -- a 500/sec ribbon would show the difference.
   */
  step(deltaSeconds: number, boneMatrix: THREE.Matrix4): void {
    const dt = Math.min(Math.max(deltaSeconds, 0), 0.1);
    this.timeMs += dt * 1000;

    for (let i = 0; i < this.capacity; i += 1) {
      const edge = this.edges[i];
      if (!edge.used) {
        continue;
      }
      edge.age += dt;
      if (edge.age > this.lifetime) {
        edge.used = false;
        this.liveCount -= 1;
      }
    }

    // GRAVITY carries the STORED verts along world +Z by `g * t^2` (`ribbons.rs:6-7`). Applied to the
    // committed vertices rather than recomputed from birth, which is the reference's own shape: the
    // edge list IS the state.
    const gravity = Number(this.definition.gravity) || 0;
    if (gravity !== 0) {
      const drop = gravity * dt * dt;
      for (let i = 0; i < this.capacity; i += 1) {
        const edge = this.edges[i];
        if (edge.used) {
          edge.az += drop;
          edge.bz += drop;
        }
      }
    }

    if (!this.visible) {
      // The gate is off: nothing new is committed, but what is already committed keeps ageing out --
      // the reference's drain, so a trail switched off mid-flight fades instead of vanishing.
      this.phase = 0;
      return;
    }

    const rate = Math.max(0, Number(this.definition.edgesPerSecond) || 0);
    this.phase += dt * rate;
    let toCommit = Math.floor(this.phase);
    if (toCommit <= 0) {
      return;
    }
    this.phase -= toCommit;
    // One edge per frame is the shipped case; a burst is capped so a long stall cannot fill the whole
    // ring with coincident edges.
    if (toCommit > this.capacity) {
      toCommit = this.capacity;
    }

    // `heightAbove`/`heightBelow` are KEYED tracks, not constants. The reference records that baking
    // value[0] made Smite's impact slash never draw, because its height is keyed `0 -> 0.167 -> 0`
    // (`benilla-formats/src/ribbons.rs:20-24`).
    const above = evaluateAnimationTrack(this.definition.heightAboveTrack, 0, this.timeMs, 0);
    const below = evaluateAnimationTrack(this.definition.heightBelowTrack, 0, this.timeMs, 0);

    const position = this.definition.position;
    scratchNode.set(position?.x ?? 0, position?.y ?? 0, position?.z ?? 0).applyMatrix4(boneMatrix);

    // THE CROSS AXIS IS WORLD +Z, not a camera-facing one, and that is deliberate. A ribbon is a
    // world-space strip and must NOT be billboarded: facing it at the camera is what would turn a
    // lightning bolt into a flat sheet that swings as the player walks, which is the failure mode this
    // project has recorded three times as two conventions meeting.
    scratchUp.set(0, 0, 1);

    for (let n = 0; n < toCommit; n += 1) {
      this.head = (this.head + 1) % this.capacity;
      const edge = this.edges[this.head];
      if (!edge.used) {
        this.liveCount += 1;
      }
      edge.used = true;
      edge.age = 0;
      edge.ax = scratchNode.x + scratchUp.x * above;
      edge.ay = scratchNode.y + scratchUp.y * above;
      edge.az = scratchNode.z + scratchUp.z * above;
      edge.bx = scratchNode.x - scratchUp.x * below;
      edge.by = scratchNode.y - scratchUp.y * below;
      edge.bz = scratchNode.z - scratchUp.z * below;
    }
  }

  /**
   * Walk the committed edges NEWEST first, which is the order the strip's `u` texcoord expects:
   * `u = age / lifetime`, so the head sits at 0 and the tail fades out at 1.
   */
  forEachEdge(visit: (edge: RibbonEdge, ageFraction: number) => void): void {
    for (let i = 0; i < this.capacity; i += 1) {
      const edge = this.edges[(this.head - i + this.capacity * 2) % this.capacity];
      if (!edge.used) {
        continue;
      }
      visit(edge, Math.min(1, edge.age / this.lifetime));
    }
  }

  /** The colour and alpha the whole strip is tinted by this frame, both keyed tracks. */
  sampleTint(out: { r: number; g: number; b: number; a: number }): void {
    let r = 1;
    let g = 1;
    let b = 1;
    const tracks = this.definition.colorTrack?.tracks;
    if (tracks && tracks.length > 0) {
      const values = tracks[0]?.values;
      if (values && values.length > 0) {
        const v = values[0];
        // `Vec3Float` decodes to an OBJECT with x/y/z, not an array -- indexing it cost this project's
        // own probe a full run of NaN.
        r = typeof v?.x === 'number' ? v.x : 1;
        g = typeof v?.y === 'number' ? v.y : 1;
        b = typeof v?.z === 'number' ? v.z : 1;
      }
    }
    out.r = r;
    out.g = g;
    out.b = b;
    out.a = Math.max(0, Math.min(1,
      evaluateAnimationTrack(this.definition.alphaTrack, 0, this.timeMs, FIXED16_SCALE)
        / FIXED16_SCALE));
  }

  /** Drop every edge. For a re-registration or a teardown. */
  reset(): void {
    for (let i = 0; i < this.capacity; i += 1) {
      this.edges[i].used = false;
    }
    this.liveCount = 0;
    this.phase = 0;
    this.timeMs = 0;
  }
}

export default RibbonRuntime;
