"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _restructure = _interopRequireDefault(require("restructure"));
var _entity = _interopRequireDefault(require("../entity"));
var _localizedStringRef = _interopRequireDefault(require("../localized-string-ref"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
var _default = (0, _entity["default"])({
  id: _restructure["default"].uint32le,
  categoryID: _restructure["default"].uint32le,
  dispelID: _restructure["default"].uint32le,
  mechanicID: _restructure["default"].uint32le,
  attributes: new _restructure["default"].Array(_restructure["default"].uint32le, 8),
  stances: _restructure["default"].uint32le,
  unknown1: new _restructure["default"].Reserved(_restructure["default"].uint32le),
  stancesExcluded: _restructure["default"].uint32le,
  unknown2: new _restructure["default"].Reserved(_restructure["default"].uint32le),
  targets: _restructure["default"].uint32le,
  targetCreatureType: _restructure["default"].uint32le,
  requiresSpellFocus: new _restructure["default"].Boolean(_restructure["default"].uint32le),
  facingCasterFlags: _restructure["default"].uint32le,
  casterAuraState: _restructure["default"].uint32le,
  targetAuraState: _restructure["default"].uint32le,
  casterAuraStateExcluded: _restructure["default"].uint32le,
  targetAuraStateExcluded: _restructure["default"].uint32le,
  casterAuraSpellID: _restructure["default"].uint32le,
  targetAuraSpellID: _restructure["default"].uint32le,
  casterAuraSpellExcluded: _restructure["default"].uint32le,
  targetAuraSpellExcluded: _restructure["default"].uint32le,
  castingTimeID: _restructure["default"].uint32le,
  recoveryTime: _restructure["default"].uint32le,
  categoryRecoveryTime: _restructure["default"].uint32le,
  interruptFlags: _restructure["default"].uint32le,
  auraInterruptFlags: _restructure["default"].uint32le,
  channelInterruptFlags: _restructure["default"].uint32le,
  procFlags: _restructure["default"].uint32le,
  procChance: _restructure["default"].uint32le,
  procCharges: _restructure["default"].uint32le,
  maxLevel: _restructure["default"].uint32le,
  baseLevel: _restructure["default"].uint32le,
  spellLevel: _restructure["default"].uint32le,
  durationID: _restructure["default"].uint32le,
  powerType: _restructure["default"].uint32le,
  manaCost: _restructure["default"].uint32le,
  manaCostPerlevel: _restructure["default"].uint32le,
  manaPerSecond: _restructure["default"].uint32le,
  manaPerSecondPerLevel: _restructure["default"].uint32le,
  rangeID: _restructure["default"].uint32le,
  speed: _restructure["default"].floatle,
  modalNextSpell: _restructure["default"].uint32le,
  stackAmount: _restructure["default"].uint32le,
  totemIDs: new _restructure["default"].Array(_restructure["default"].uint32le, 2),
  reagentIDs: new _restructure["default"].Array(_restructure["default"].uint32le, 8),
  reagentCounts: new _restructure["default"].Array(_restructure["default"].uint32le, 8),
  equippedItemClassID: _restructure["default"].int32le,
  equippedItemSubClassMask: _restructure["default"].int32le,
  equippedItemInventoryTypeMask: _restructure["default"].int32le,
  effectIDs: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectDieSides: new _restructure["default"].Array(_restructure["default"].int32le, 3),
  effectBaseDices: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectDicesPerLevel: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectRealPointsPerLevel: new _restructure["default"].Array(_restructure["default"].floatle, 3),
  effectBasePoints: new _restructure["default"].Array(_restructure["default"].int32le, 3),
  effectMechanicIDs: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectImplicitTargets: new _restructure["default"].Array(_restructure["default"].uint32le, 6),
  effectRadiusIDs: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectAurasIDs: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectAmplitudes: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectProcValues: new _restructure["default"].Array(_restructure["default"].floatle, 3),
  effectChainTargets: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectItemTypes: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectMiscValues: new _restructure["default"].Array(_restructure["default"].int32le, 6),
  effectTriggerSpells: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  effectPointsPerComboPoint: new _restructure["default"].Array(_restructure["default"].floatle, 3),
  effectSpellClassMasks: new _restructure["default"].Array(_restructure["default"].uint32le, 9),
  visualIDs: new _restructure["default"].Array(_restructure["default"].uint32le, 2),
  iconID: _restructure["default"].uint32le,
  activeIconID: _restructure["default"].uint32le,
  priority: _restructure["default"].uint32le,
  name: _localizedStringRef["default"],
  rank: _localizedStringRef["default"],
  description: _localizedStringRef["default"],
  toolTip: _localizedStringRef["default"],
  manaCostPercentage: _restructure["default"].uint32le,
  startRecoveryCategory: _restructure["default"].uint32le,
  startRecoveryTime: _restructure["default"].uint32le,
  maxTargetLevel: _restructure["default"].uint32le,
  familyName: _restructure["default"].uint32le,
  familyFlags: new _restructure["default"].Array(_restructure["default"].uint32le, 3),
  maxAffectedTargets: _restructure["default"].uint32le,
  damageClass: _restructure["default"].uint32le,
  preventionType: _restructure["default"].uint32le,
  stanceBarOrder: _restructure["default"].uint32le,
  damageMultiplier: new _restructure["default"].Array(_restructure["default"].floatle, 3),
  minFactionID: _restructure["default"].uint32le,
  minReputation: _restructure["default"].uint32le,
  requiredAuraVision: _restructure["default"].uint32le,
  totemCategoryIDs: new _restructure["default"].Array(_restructure["default"].uint32le, 2),
  areaGroupID: _restructure["default"].int32le,
  schoolMask: _restructure["default"].uint32le,
  runeCostID: _restructure["default"].uint32le,
  spellMissileID: _restructure["default"].uint32le,
  powerDisplayID: _restructure["default"].uint32le,
  effectBonusMultipliers: new _restructure["default"].Array(_restructure["default"].floatle, 3),
  unknown3: new _restructure["default"].Reserved(_restructure["default"].uint32le)
});
exports["default"] = _default;